import { useParams, Navigate } from "react-router-dom";
import { HeaderSection } from "@/components/report/HeaderSection";
import { ScoreAnalytics } from "@/components/report/ScoreAnalytics";
import { InterviewSection } from "@/components/report/InterviewSection";
import { StrengthsAndImprovements } from "@/components/report/StrengthsAndImprovements";
import { InterviewerInsights } from "@/components/report/InterviewerInsights";
import { ResourcesSection } from "@/components/report/ResourcesSection";
import { getCandidateById, candidates } from "@/data/candidates";

const Index = () => {
  const { candidateId } = useParams<{ candidateId?: string }>();

  // If no candidate ID, default to first candidate
  if (!candidateId) {
    return <Navigate to={`/${candidates[0].id}`} replace />;
  }

  const candidate = getCandidateById(candidateId);

  // If candidate not found, redirect to first candidate
  if (!candidate) {
    return <Navigate to={`/${candidates[0].id}`} replace />;
  }

  // Build resources array
  const resources = [
    {
      title: "Candidate Resume",
      description: "Full resume with education, skills, and experience details",
      url: candidate.resumeUrl,
      type: "resume" as const,
    },
    {
      title: "Topin Tech Report",
      description: "Comprehensive assessment and statistics from Topin platform",
      url: candidate.topinReportUrl,
      type: "report" as const,
    },
    {
      title: "DSA Interview Recording",
      description: `TR1 Interview with ${candidate.tr1.interviewer}`,
      url: candidate.tr1.recordingUrl,
      type: "recording" as const,
    },
    {
      title: "Technical Interview Recording",
      description: `TR2 Interview with ${candidate.tr2.interviewer}`,
      url: candidate.tr2.recordingUrl,
      type: "recording" as const,
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-background via-muted/40 to-background">
      <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-8">
        {/* Header */}
        <HeaderSection
          candidateName={candidate.name}
          recommendation={candidate.recommendation}
          overallScore={candidate.overallScore}
          resumeUrl={candidate.resumeUrl}
          topinReportUrl={candidate.topinReportUrl}
          candidateId={candidateId}
        />

        {/* Content sections */}
        <div className="mt-8 space-y-8">
          {/* Score Analytics */}
          <ScoreAnalytics
            overallScore={candidate.overallScore}
            codingScore={candidate.codingScore}
            dsaScore={candidate.dsaScore}
          />

          {/* Interview Sections */}
          <InterviewSection {...candidate.tr1} />
          <InterviewSection {...candidate.tr2} />

          {/* Strengths & Improvements */}
          <StrengthsAndImprovements
            strengths={candidate.strengths}
            improvements={candidate.improvements}
          />

          {/* Interviewer Insights */}
          <InterviewerInsights
            hiringSignal={candidate.interviewerInsights.hiringSignal}
            confidenceLevel={candidate.interviewerInsights.confidenceLevel}
            industryReadiness={candidate.interviewerInsights.industryReadiness}
            summary={candidate.interviewerInsights.summary}
          />

          {/* Resources */}
          <ResourcesSection resources={resources} />
        </div>

        {/* Footer */}
        <footer className="mt-12 border-t border-border pt-6 text-center">
          <p className="text-sm text-muted-foreground">
            Report generated by NxtWave Employability Assessment Platform
          </p>
          <p className="mt-1 text-xs text-muted-foreground/70">
            Confidential – For authorized hiring partners only
          </p>
        </footer>
      </div>
    </div>
  );
};

export default Index;
